version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=goaly
      - POSTGRES_PASSWORD=goaly
      - POSTGRES_DB=goaly
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goaly"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=goaly
      - DB_USER=goaly
      - DB_PASS=goaly
      - PORT=8080
      - HOST=0.0.0.0
      - PASSWORD=password
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80"
    environment:
      - API_HOST=backend
      - PORT=8080
      - AUTH0_DOMAIN="dev-jgk07h16kswx1avk.us.auth0.com"
      - AUTH0_CLIENT_ID="99OYxyrtsFjHuNd3NYsbBt7bC5M0vB8P"


volumes:
  db:
    driver: local
